### ISSUE TITLE
async support

### ISSUE THREAD

**Issue by ahmetalpbalkan** [ziyasal/InfluxDB.Net#2]
As InfluxDB works over HTTP REST, it must be easy to make all client methods async by using HttpClient from Microsoft.Net.Http package. I am not using the library but if I needed it, I'd certainly seek for asynchronous call support as non-blocking io matters a lot nowadays.

**Comment by ahmetalpbalkan** [comment]
@ziyasal, this doesn't solve the async support?

**Comment by ahmetalpbalkan** [comment]
okay seems like c5e61c94dddaa5c69dd061f1c2d093efeb00cc47 fixes this.

**Comment by ziyasal** [comment]
My fault, I have closed issue with wrong commit. So it cause confusion.
