### ISSUE TITLE
Compatibility with 0.9.0

### ISSUE THREAD

**Issue by jamesholcomb** [ziyasal/InfluxDB.Net#5]
Getting this error running the unit tests in both Xamarin 5.9.3 (Mono 4.0.1) and VS2015 RC1 against 0.9.0-rc31

    InfluxDB.Net.InfluxDbApiException : InfluxDb API responded with status code=NotFound, response=404 page not found

curl works ok:

```
~/InfluxDB.Net [master|✚ 5…56] 
10:02 AM $ curl -G "http://localhost:8086/ping" -v
* Hostname was NOT found in DNS cache
*   Trying ::1...
* Connected to localhost (::1) port 8086 (#0)
> GET /ping HTTP/1.1
> User-Agent: curl/7.37.1
> Host: localhost:8086
> Accept: */*
> 
< HTTP/1.1 204 No Content
< Request-Id: f1c7a8db-0b93-11e5-8209-000000000000
< X-Influxdb-Version: 0.9.0-rc31
< Date: Fri, 05 Jun 2015 15:02:54 GMT
< 
* Connection #0 to host localhost left intact
```

**Comment by ziyasal** [comment]
Hi @jamesholcomb, I didn't check API changes yet. I'll take look asap.

**Comment by jamesholcomb** [comment]
Yep, lots of breaking changes in 0.9.0.  I forked the repo and began converting.  The basics (read/write) and the new line protocol format are working.  I'll commit soon so you can take a look.

**Comment by lucasjans** [comment]
Is the current client good enough to write data? That's all I'm looking for with my .NET application.

**Comment by poxet** [comment]
It would be great if there could still be a client class implementation that supports 0.8 as well.

I am developing "influxdb-collector" that uses this project, and need support for both influx version 0.8 and 0.9.

Tell me if I can contribute.

**Comment by jamesholcomb** [comment]
My fork supports read/write functions for 0.9.2.  I don't plan on concurrent 0.8 support.

Issues/PRs welcome.

**Comment by ziyasal** [comment]
Hi @jamesholcomb, Have you any plan to merge your changes to main repo? It'd be great.

**Comment by jamesholcomb** [comment]
Hi @ziyasal, would be happy to...since you originated the code, perhaps you could take a look to see if you have any suggestions before the merge.

There is still a bit of work remaining to refactor the db admin related API functions.

**Comment by pootzko** [comment]
Hi, did the new changes get merged back into the original repo in the end or is the InfluxDB.Net project dead?

@jamesholcomb - did you manage make the lib work with 0.9.x? Any updates on this? :)

thanks

**Comment by kmacmcfarlane** [comment]
Also curious about the status of 0.9 support? Especially as version 0.10 just landed this week.

**Comment by ziyasal** [comment]
hi @jamesholcomb @kmacmcfarlane  @pootzko @poxet I have started to work on  v0.9.x and v0.10x support.

**Comment by poxet** [comment]
Please have a look at my fork. It has support for version 0.9x (0.9.2, 0.9.5 and 0.9.6) and I am testing for 0.10.x now with the work from @pootzko.

To get this working I am using dependency injhection. There is also a "Auto" connector that pings influxDB and automatically uses the correct implementation for the  version on the server.

I think it is important for a tool like this to support older versions along with new ones.

**Comment by pootzko** [comment]
I think that resolving the influx version in runtime is not really a good idea. If you want good performance during writes, you want to avoid an unnecessary preflight request just for the sake of figuring out which version of influx client you need. It tends to clog up free TCP sockets. Perhaps as an optional feature but by default - I believe people shouldn't rely on that. It's easy enough to figure out which version of the API you're using anyway.

Btw. I forked this whole repo a few months ago and made a new nuget called InfluxData.Net which currently supports influx v0.9.6, kapacitor v0.10.1 and I will quite soon check/test/deploy influx v0.10 as well.. With no replies this seemed dead and I needed proper support for v0.9.6 so I kind of did my own thing there. This codebase was huge help however.

**Comment by poxet** [comment]
Cool, I really need support for version v0.10 as well! Was planning on working on that too.

I see your point with the "Auto" configuration. It is just a single ping call, that is built into the client and also checks that the server is online. But perhaps the last version should be default and the "auto" an optional version.

I use the "Auto" configuration in a third party component where I do not know what version of influxDB the end users are using. This would save a little bit of configuration. And the extra call have not yet been a problem.

**Comment by poxet** [comment]
The project now supports multiple versions.
