### ISSUE TITLE
Continuous build to nuget.org

### ISSUE THREAD

**Issue by poxet** [ziyasal/InfluxDB.Net#7]
It would be great if the new versions where built and published to 
https://www.nuget.org/packages/InfluxDB.Net-Main/ more regularly. That would make it easier to make use of the latest version of the project.

**Comment by RichiCoder1** [comment]
Or myget for that matter :)

**Comment by poxet** [comment]
I have a continuous build for the repositories in my fork (https://github.com/poxet/InfluxDB.Net/tree/MultipleVersions). They are now posted to http://thargelion.se/nuget

This made it easier for me to use the nuget package in another project. But an official continuous build to nuget.org or to myget would be better. :)

**Comment by poxet** [comment]
Just fixed the continuous deploy here...
https://www.nuget.org/packages/InfluxDB.Net-Main/
